# Dependencies
markdown:           kramdown 
gems:
        - jekyll-paginate
        - jekyll-gist
         
# Permalinks
permalink:           pretty

# Setup
title:            "<center> Thibault <br/> Allart </center>"            
tagline:          'Data Scientist'
description:      '' 
url:              http://thibaultallart.github.io
baseurl:          
homeurl:          /

author:
  name:           'Thibault Allart'

paginate:         5

# Custom vars
version:          1.0.0

        
github:           
  repo:           https://github.com/thibaultallart
